### ISSUE TITLE
Question: supported CPUs

### ISSUE THREAD

**Issue by dbermond** [oneapi-src/oneVPL-cpu#4]
What CPUs are supported in this CPU runtime implementation? This information seems to be missed from the readme file.

Is non-Intel supported? Are older CPUs like Haswell supported?

**Comment by mav-intel** [comment]
Minimal requirement is 5th Generation Intel Core™ Processors (formerly Broadwell) CPUs (Xeon E5-v4) or newer (required by the underlying SVT implementations). We have not validated the CPU implementation on non-intel CPUs but it may work.

**Comment by dbermond** [comment]
@mav-intel Thank you for the clarification.

I think the readme could contain such information.

Closing.
