### ISSUE TITLE
GTest fails with deprecated copy warning on newer compilers (clang-14)

### ISSUE THREAD

**Issue by codyjack5** [oneapi-src/oneVPL-cpu#40]
Clang-14 warns on implicit copy constructors (enabled with -Wdeprecated)

The CPU implementation tests fails to build with this compiler. Building with -DBUILD_TESTS=OFF works. 

This was fixed upstream in Google Test ; can you please take a look to bump the version? https://github.com/google/googletest/pull/2815

Looks like it was fixed in 1.11.0. Gtest version is 1.8.1 I think.

**Comment by mav-intel** [comment]
Thanks for bringing this to our attention. We'll upgrade the version.

**Comment by mav-intel** [comment]
Fixed in eb883eb574375664c6e5bd7f80ceb94acf8d7140
