### ISSUE TITLE
source script/bootstrap

### ISSUE THREAD

**Issue by LLL-YUE** [oneapi-src/oneVPL-cpu#42]
After running the "source script/bootstrap", the terminal will exit suddenly while installing something. How to deal with this situation?

**Comment by LLL-YUE** [comment]
And after running the "script/build", it shows that Unable to find required VPL component: dispatcher

**Comment by mav-intel** [comment]
Hi @LLL-YUE,
Can you please share your OS, command lines run, and logs? We need more information to help you.

>And after running the "script/build", it shows that Unable to find required VPL component: dispatcher

This means that VPL dispatcher could not be found.  The dispatcher (development files) being installed is a prerequisite to building the CPU implementation. 

Did you follow all the steps in [INSTALL.md](https://github.com/oneapi-src/oneVPL-cpu/blob/master/INSTALL.md)?
